// 用于 localStorage 存取 Item 时候的名字定义部分。
export default {
    searchPaths: "SearchPaths",
    localVer: "localVer",
    audio: "audio",
    uuid: "uuid",
    account: "accout",
    password: "password",
    manifestMain: "manifestMain",
    lobbyPath: "game",
    certificate: "certificateToken",
    ddzTimes: "ddzTimes",
    pdkTimes: "pdkTimes",
    hotUpdateTime: "hotUpdateTime",
    devFlag: "devFlag",
    ipList: "pipipi",
    problemCD: "problemCD",
    guideState: "guideState",
    complainTime: "complainTime",
    officialUrl: 'officialUrl',
    weChat: 'weChat',
    qq: 'qq',
    deviceToken: 'deviceToken',
}
